export interface DruModel {
  id: string;
  hospital_code: string;
  hcode: string;
  hn: string;
  an: string;
  clinic: string;
  person_id: string;
  date_serv: string;
  did: string;
  didname: string;
  amount: string;
  drugprice: string;
  drugcost: string;
  didstd: string;
  unit: string;
  unit_pack: string;
  seq: string;
  drugremark: string;
  pa_no: string;
  totcopay: string;
  use_status: string;
  total: string;
  sigcode: string;
  sigtext: string;
  provider: string;
  sp_item: string;
  status: number;
}
